version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-sam: circleci/aws-sam-serverless@6.0.1

jobs:
  build-layer:
    environment:
      NODE_ENV: "production"
      DISABLE_OPENCOLLECTIVE: "true"
      SAM_CLI_TELEMETRY: 0

    docker:
      - image: cimg/node:lts

    steps:
      - checkout
      - run: node --version  
      - aws-cli/setup
      - aws-sam/install      
      
      # - restore_cache:
      #    key: v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
          
      - run: | 
          NODE_ENV=development
          npm ci 
          alias dnf=yum
          npm run build

      # - save_cache:
      #    key: v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
      #    paths:
      #      - '/root/.npm/**/*'

# artifacts:
#  files:
#    - .aws-sam/**/*

workflows:
  build-layer-workflow:
    jobs:
      - build-layer



