version: 2.1

jobs:
  build-layer:
    environment:
      NODE_ENV: "production"
      DISABLE_OPENCOLLECTIVE: "true"
      SAM_CLI_TELEMETRY: 0

    docker:
      - image: cimg/node:lts

    steps:
      - checkout
      - run: node --version    
      - run: wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-arm64.zip  
      - run: unzip aws-sam-cli-linux-arm64.zip -d sam-installation
      - run: sudo ./sam-installation/install
      
      # - restore_cache:
      #    key: v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
          
      - run: | 
          NODE_ENV=development
          npm ci 
          ls
          npm run build

      # - save_cache:
      #    key: v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
      #    paths:
      #      - '/root/.npm/**/*'

# artifacts:
#  files:
#    - .aws-sam/**/*

workflows:
  build-layer-workflow:
    jobs:
      - build-layer



